
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 20 13:33:25 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 30;
  public static final int FSI = 11;
  public static final int TANTQUE = 27;
  public static final int MULT = 6;
  public static final int EGAL = 26;
  public static final int REPETER = 28;
  public static final int SI = 10;
  public static final int FIN = 24;
  public static final int LIRE = 2;
  public static final int OU = 19;
  public static final int INF = 15;
  public static final int NON = 20;
  public static final int PAROUV = 8;
  public static final int DIV = 7;
  public static final int EGALEGAL = 16;
  public static final int PLUS = 4;
  public static final int DEBUT = 23;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 31;
  public static final int MOINS = 5;
  public static final int ET = 18;
  public static final int IDF = 35;
  public static final int SINON = 13;
  public static final int ALORS = 12;
  public static final int PARFER = 9;
  public static final int CONSTANTEINT = 32;
  public static final int CONSTANTEBOOL = 33;
  public static final int PROGRAMME = 22;
  public static final int POINTVIRGULE = 21;
  public static final int FINTANTQUE = 29;
  public static final int SUP = 14;
  public static final int DIFF = 17;
  public static final int ENTIER = 25;
  public static final int CHAINE = 34;
  public static final int ECRIRE = 3;
}

